name: Setup Gradle Wrapper

on: [workflow_dispatch]

jobs:
  setup-wrapper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Generate Gradle Wrapper
      run: |
        # Download gradle temporarily to create wrapper
        wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
        unzip gradle-8.7-bin.zip
        ./gradle-8.7/bin/gradle wrapper --gradle-version 8.7
        
        # Clean up
        rm -rf gradle-8.7*
    - name: Commit Wrapper Files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add gradlew gradlew.bat gradle/wrapper
        git commit -m "Add proper Gradle wrapper files"
        git push
