name: Prior2NameChange

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

    steps:
      - uses: actions/checkout@v4

      # This will quickly restore cached Android SDK components
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cache: true
          cmdline-tools-version: 'latest'
          build-tools-version: '34.0.0'
          platform-version: '34'
          ndk-version: '25.2.9519653'

      # License acceptance is still needed but fast
      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # This will restore Gradle dependencies from cache
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Fast setup using cached Gradle version
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.2'
          cache-read-only: true  # Important for subsequent runs

      # The build will be faster as dependencies are cached
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --build-cache --stacktrace
          # Removed 'clean' to preserve incremental builds
          # Removed '--refresh-dependencies' to use cached deps
      
      - name: List Generated APK Files
        run: ls -l app/build/outputs/apk/debug/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
