# .github/workflows/android.yml
name: Pulledfrom Pavlo Android CI

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Clean all Gradle caches before starting
      - name: Clean Gradle Caches
        run: |
          echo "Cleaning Gradle caches..."
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/ # This line is important for wrapper cache
          rm -rf ${{ github.workspace }}/.gradle/caches/
          echo "Gradle caches cleaned."

      # NEW: Cache Gradle dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # NEW: Cache Android SDK components
      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            $ANDROID_HOME/platforms
            $ANDROID_HOME/build-tools
            $ANDROID_HOME/cmdline-tools
            $ANDROID_HOME/ndk
            ~/.android/cache # Cache AndroidX libraries/SDK build cache
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle*', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.2'
          # Note: This action has its own caching. Combining with actions/cache can be redundant.
          # You might want to evaluate if you need both.

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cache: true # This action also has its own caching for SDK components.
          cmdline-tools-version: 'latest'
          build-tools-version: '34.0.0'
          platform-version: '34'
          ndk-version: '25.2.9519653'

      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean assembleDebug --refresh-dependencies --stacktrace
      
      # NEW STEP: List contents of the APK output directory
      - name: List Generated APK Files
        run: ls -l app/build/outputs/apk/debug/
        

                  
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BWCTrans-APK
          path: app/build/outputs/apk/debug/BWCTrans-debug.apk

        


           
