name: Android DataBinding Build Fix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

    steps:
      - uses: actions/checkout@v4

      - name: Fix File Permissions
        run: |
          chmod +x gradlew
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clean Project
        run: |
          ./gradlew clean
          rm -rf build/ .gradle/ app/build/

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: '34.0.0'
          platform-version: '34'
          ndk-version: '25.2.9519653'

      - name: Build with Debug Info
        run: |
          ./gradlew assembleDebug --stacktrace
        #  --no-daemon \
        #  -Pandroid.debug.obsoleteApi=true \
        #  -Pandroid.databinding.enableV2=true
